[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.97.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

 [[redirects]]
  from = "/author/yuyan-ruan1/"
  to = "https://github.com/RYY0722"
  force = true

 [[redirects]]
  from = "/author/xiaoyu-zheng/"
  to = "https://github.com/xiaoyu-z/"
  force = true

 [[redirects]]
  from = "/author/yu-cai/"
  to = "https://caiyu6666.github.io/"
  force = true

 [[redirects]]
  from = "/author/yingxue-xu/"
  to = "https://innse.github.io/"
  force = true

 [[redirects]]
  from = "/author/haoxuan-che/"
  to = "https://www.linkedin.com/in/chehx/"
  force = true
