[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.97.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

 [[redirects]]
  from = "/author/yu-yan-ruan/"
  to = "https://wang-lab.hkust.edu.hk/people/cv_html/yuyan_cv.html"
  force = true

 [[redirects]]
  from = "/author/xiao-yu-zheng/"
  to = "https://linkedin.com/in/xiaoyuzlovesds/"
  force = true

 [[redirects]]
  from = "/author/yu-cai/"
  to = "https://caiyu6666.github.io/"
  force = true

 [[redirects]]
  from = "/author/ying-xue-xu/"
  to = "https://innse.github.io/"
  force = true

 [[redirects]]
  from = "/author/hao-xuan-che/"
  to = "https://www.linkedin.com/in/chehx/"
  force = true

 [[redirects]]
  from = "/author/jia-xin-zhuang/"
  to = "https://jiaxinzhuang.github.io/"
  force = true

 [[redirects]]
  from = "/author/an-dong-tan/"
  to = "https://www.linkedin.com/in/andong-tan-785661122/"
  force = true

 [[redirects]]
  from = "/author/hai-bo-jin/"
  to = "http://jhb86253817.github.io/"
  force = true

 [[redirects]]
  from = "/author/zheng-rui-guo/"
  to = "https://github.com/GzrDavidRicardo"
  force = true

 [[redirects]]
  from = "/author/cheng-jin/"
  to = "https://chengjin.netlify.app/"
  force = true

 [[redirects]]
  from = "/author/lu-yang-jin/"
  to = "https://llyxc.github.io/"
  force = true

 [[redirects]]
  from = "/author/jia-bo-ma/"
  to = "https://github.com/birkhoffkiki"
  force = true

